### ISSUE TITLE
Example to use this package for flutter web

### ISSUE THREAD

**Issue by nablidev** [fluttercommunity/flutter_google_places#120] opened 2020-06-04 15:33 UTC
I need an example on how to use this package on flutter for web to know how to include the google places API correctly. The package for web is showing me no search results for the moment.

**Comment by KevMorelli** [comment] 2020-06-05 07:14
Check [Issue 93](https://github.com/fluttercommunity/flutter_google_places/issues/93#issuecomment-628361440) that explains what problems there are with web and some temporary solutions

**Comment by angwandi** [comment] 2020-06-11 18:46
Any better solution coming sometime soon? @KevMorelli

**Comment by suhmeanhuck** [comment] 2021-03-29 03:11
I saw that flutter_google_places states that it is compatible with flutter web but I just wanted to check if it only works with the workaround above? 

Trying to search for "che" shows no results and throws the error:

[flutter_google_places_hoc081098] headers={}
[flutter_google_places_hoc081098] input=ch location=null origin=null
[flutter_google_places_hoc081098] ERROR XMLHttpRequest error. dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/http/src/browser_client.dart 71:22                                       <fn>
dart-sdk/lib/async/zone.dart 1612:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 152:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 704:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 733:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 530:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>

This [post](https://stackoverflow.com/questions/64458696/in-flutter-web-getting-xmlhttprequest-error-while-making-http-call) advised, "In most cases of Flutter API use, add Access-Control-Allow-Origin value in header might resolve the issue," but I don't think that is possible for the "apiHeaders" parameter.

Is it advised to avoid using this package for production on web at this time due to it only working with the workaround?

**Comment by juliansteenbakker** [comment] 2022-03-15 21:14
Duplicate of #93, for now web is not supported.

**Closed by juliansteenbakker** 2022-03-15 21:14 UTC
