### ISSUE TITLE
 Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by DineshTaral** [fluttercommunity/flutter_google_places#165] opened 2021-04-20 17:31 UTC
I'm not able to search any place don't know why, getting below issue 

[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
#0      PlacesAutocompleteState.doSearch (package:flutter_google_places/src/flutter_google_places.dart:436:28)

**Comment by diggdiganta** [comment] 2021-04-20 19:10
Same problem

**Comment by paghardik** [comment] 2021-04-21 12:45
Releated #164

**Comment by ysoofiyani** [comment] 2021-04-21 17:54
Same issue

**Comment by farhantariq916** [comment] 2021-04-22 10:21
Also facing same issue :(

**Comment by in3mo** [comment] 2021-04-22 12:57
You have to send all the parameters of the function:
`    Prediction p = await PlacesAutocomplete.show(
      offset: 0,
      radius: 1000,
      types: [],
      strictbounds: false,
      region: "ar",
      context: context,
      apiKey: kGoogleApiKey,
      mode: Mode.overlay, // Mode.fullscreen
      language: "es",
      components: [Component(Component.country, "ar")]
    );`

**Comment by cyuket** [comment] 2021-05-04 11:02
Thank you @in3mo

**Comment by hoc081098** [comment] 2021-05-09 15:27
Trying it: https://pub.dev/packages/flutter_google_places_hoc081098

**Comment by AnasMasri** [comment] 2021-05-26 11:42
Null safety migration is not implemented in the right way, strictbounds, components and types aren't required but they're used with Null Check operator "!" which technically means they're required and will have to pass them as a workaround for now.

**Comment by dungnc** [comment] 2021-06-04 09:33
> language: "es", components: [Component(Component.country, "ar")]

Which I should use it when I want to search place all of world?

**Comment by dungnc** [comment] 2021-06-04 09:33
> You have to send all the parameters of the function:
> ` Prediction p = await PlacesAutocomplete.show( offset: 0, radius: 1000, types: [], strictbounds: false, region: "ar", context: context, apiKey: kGoogleApiKey, mode: Mode.overlay, // Mode.fullscreen language: "es", components: [Component(Component.country, "ar")] );`

Which I should use it when I want to search place all of world?

**Comment by naqash-smrt-is** [comment] 2021-06-05 17:40
![image](https://user-images.githubusercontent.com/84722271/120900584-f4b23300-c64e-11eb-875d-4cb4aead2c95.png)
Still getting it

**Comment by naqash-smrt-is** [comment] 2021-06-06 09:49
> Used as custom widget
> ![image](https://user-images.githubusercontent.com/84722271/120900607-17dce280-c64f-11eb-9c28-8fb193887072.png)
> 
> ![image](https://user-images.githubusercontent.com/84722271/120900584-f4b23300-c64e-11eb-875d-4cb4aead2c95.png)
> Still getting it

Resolved this by adding the following options in constructor
![image](https://user-images.githubusercontent.com/84722271/120920063-5669b000-c6d6-11eb-922f-bd4004211586.png)

**Comment by juliansteenbakker** [comment] 2021-11-19 14:48
Duplicate of #164, expect an update soon.

**Closed by juliansteenbakker** 2021-11-19 14:48 UTC

**Comment by ravindra6016** [comment] 2022-04-28 06:19
> You have to send all the parameters of the function: ` Prediction p = await PlacesAutocomplete.show( offset: 0, radius: 1000, types: [], strictbounds: false, region: "ar", context: context, apiKey: kGoogleApiKey, mode: Mode.overlay, // Mode.fullscreen language: "es", components: [Component(Component.country, "ar")] );`

it is working thanks
