### ISSUE TITLE
Unhandled Exception: Connection closed before full header was received

### ISSUE THREAD

**Issue by sumitrvi** [fluttercommunity/flutter_google_places#138] opened 2021-01-16 05:19 UTC
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Connection closed before full header was received
E/flutter (10708): #0      IOClient.send (package:http/src/io_client.dart:62:7)
E/flutter (10708): <asynchronous suspension>
E/flutter (10708): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:91:38)
E/flutter (10708): #2      BaseClient.get (package:http/src/base_client.dart:27:7)
E/flutter (10708): #3      GoogleWebService.doGet (package:google_maps_webservice/src/utils.dart:61:23)
E/flutter (10708): #4      GoogleMapsPlaces.autocomplete (package:google_maps_webservice/src/places.dart:169:46)
E/flutter (10708): #5      PlacesAutocompleteState.doSearch (package:flutter_google_places/src/flutter_google_places.dart:406:33)
E/flutter (10708): #6      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (10708): #7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10708): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (10708): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (10708): #10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (10708): #11     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
E/flutter (10708): #12     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
E/flutter (10708): #13     _StartWithStreamSink.add (package:rxdart/src/transformers/start_with.dart:16:10)
E/flutter (10708): #14     forwardStream.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:34:49)
E/flutter (10708): #15     forwardStream.runCatching (package:rxdart/src/utils/forwarding_stream.dart:24:12)
E/flutter (10708): #16     forwardStream.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:34:28)
E/flutter (10708): #17     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (10708): #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10708): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (10708): #20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (10708): #21     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (10708): #22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (10708): #23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (10708): #24     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (10708): #25     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10708): #26     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (10708): #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (10708): #28     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (10708): #29     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10708): #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (10708): #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (10708): #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (10708): #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (10708):

**Comment by KevMorelli** [comment] 2021-04-09 04:58
unable to reproduce, can you test with version 0.3.0 ?

**Comment by badelectron77** [comment] 2021-04-26 07:44
Same error here. Unable to fix.

**Comment by DSMalaviya** [comment] 2021-10-05 10:03
E/flutter ( 8496): #0      IOClient.send
package:http/src/io_client.dart:66
E/flutter ( 8496): <asynchronous suspension>
E/flutter ( 8496): #1      BaseClient._sendUnstreamed
package:http/src/base_client.dart:93
E/flutter ( 8496): <asynchronous suspension>
E/flutter ( 8496): #2      GoogleMapsPlaces.autocomplete
package:google_maps_webservice/src/places.dart:171


unable to find issue??

**Comment by juliansteenbakker** [comment] 2021-11-19 14:51
Duplicate of #135

**Closed by juliansteenbakker** 2021-11-19 14:51 UTC
Labels: Waiting for answer
