### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by panchalAlpit** [fluttercommunity/flutter_google_places#171] opened 2021-08-05 06:39 UTC
Because flutter_google_places >=0.3.0 depends on google_maps_webservice ^0.0.20-nullsafety.3 which depends on json_annotation ^4.0.0, flutter_google_places >=0.3.0 requires json_annotation ^4.0.0.
So, because legit depends on both flutter_google_places ^0.3.0 and json_annotation ^3.0.0, version solving failed.
pub get failed (1; So, because legit depends on both flutter_google_places ^0.3.0 and json_annotation ^3.0.0, version solving failed.)

**Comment by juliansteenbakker** [comment] 2021-11-19 14:47
This is a duplicate of #164. Expect a fix soon.

**Closed by juliansteenbakker** 2021-11-19 14:47 UTC
