### ISSUE TITLE
update rx_dart version to 0.27.1

### ISSUE THREAD

**Issue by prajwal27** [fluttercommunity/flutter_google_places#166] opened 2021-06-06 17:11 UTC
from rx_dart 0.27, there's a breaking change. Hence projects depending on this package as well as rx_dart might face issues.

**Comment by hoc081098** [comment] 2021-06-12 15:16
Try this: https://pub.dev/packages/flutter_google_places_hoc081098

**Comment by prajwal27** [comment] 2021-06-16 05:24
@hoc081098  does it work with latest version of rx_dart?

**Comment by hoc081098** [comment] 2021-06-16 05:39
> @hoc081098  does it work with latest version of rx_dart?
> 

Yes

**Comment by juliansteenbakker** [comment] 2021-11-19 14:48
Duplicate of #164. Expect an update soon.

**Closed by juliansteenbakker** 2021-11-19 14:48 UTC
