### ISSUE TITLE
XMLHttpRequest error on Flutter web

### ISSUE THREAD

**Issue by bibash28** [fluttercommunity/flutter_google_places#163] opened 2021-04-09 03:51 UTC
Code:
    Prediction prediction = await PlacesAutocomplete.show(
      context: context,
      logo: Container(height: 1),
      apiKey: googleApiKey,
      hint: S.of(context).Search_Address,
      mode: Mode.overlay,
      language: languageCode,
      components: [Component(Component.country, "us")],
      location:
          Location(lat: userLocation.latitude, lng: userLocation.longitude),
      strictbounds: false,
      types: [],
      onError: (e) => showSnackBar(context, e.errorMessage),
    );
    
    
Error :
Error: XMLHttpRequest error.
    C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/http/src/browser_client.dart 71:22                                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1612:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 152:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 704:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 733:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 530:7                                         [_complete]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>

    at Object.createErrorWithStack (http://localhost:57008/dart_sdk.js:5347:12)
    at Object._rethrow (http://localhost:57008/dart_sdk.js:39349:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:57008/dart_sdk.js:39343:13)
    at Object._microtaskLoop (http://localhost:57008/dart_sdk.js:39175:13)
    at _startMicrotaskLoop (http://localhost:57008/dart_sdk.js:39181:13)
    at http://localhost:57008/dart_sdk.js:34688:9

**Comment by KevMorelli** [comment] 2021-04-09 05:46
@bibash28 It's a CORS issue.

For now the fastest way to fix it it's here
https://github.com/fluttercommunity/flutter_google_places/issues/93#issuecomment-652261230

**Comment by minhduc1827** [comment] 2021-06-20 13:38
Hello all, is issue fixed because when i use the heroku proxy it's very limit reading.
Thanks all

**Comment by jtmuller5** [comment] 2021-08-06 21:18
Any update on this?

**Comment by achinverma** [comment] 2021-08-25 07:31
i am also getting the same issue, Please suggest fix asap.

**Comment by juliansteenbakker** [comment] 2022-03-15 21:16
Duplicate of #93, for now web is not supported.

**Closed by juliansteenbakker** 2022-03-15 21:16 UTC
Labels: In Progress
